apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: anime-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: anime-api-deployment
  minReplicas: 4 # if this is lower than 4 then deployment will be scaled down to lower than 4.
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60