apiVersion: v1
kind: Secret
metadata:
  name: acr-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuYWdwMjAyNnJieC5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoibmFncDIwMjZyYngiLCJwYXNzd29yZCI6IkJucW9hQkJwZGVJQ2RWT0djbUg4cm41U21FaFNmVlVsSWx0WVE2b2ZySm1mZ051ME9hbkVKUVFKOTlDRkFDR2hzbEJFcWc3TkFBQUNBWkNSclNuWSIsImF1dGgiOiJibUZuY0RJd01qWnlZbmc2UW01eGIyRkNRbkJrWlVsRFpGWlBSMk50U0RoeWJqVlRiVVZvVTJaV1ZXeEpiSFJaVVRadlpuSktiV1puVG5Vd1QyRnVSVXBSVVVvNU9VTkdRVU5IYUhOc1FrVnhaemRPUVVGQlEwRmFRMUp5VTI1WiJ9fX0=