apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anime-db-statefulset
spec:
  serviceName: "anime-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: anime-db-custom-postgres
  template:
    metadata:
      labels:
        app: anime-db-custom-postgres
    spec:
      containers:
        - name: postgres
          image: ghcr.io/code-licker/nagp-2026-anime-db:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: dbport
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: anime-db-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: anime-db-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: anime-db-secrets
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: anime-db-data-volume
              mountPath: /var/lib/postgresql/data 
      volumes:
        - name: anime-db-data-volume
          persistentVolumeClaim:
            claimName: anime-db-pvc 