services:
  postgres-db:
    image: postgres:15-alpine
    container_name: local_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psswd
      POSTGRES_DB: anime_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d anime_db"]
      interval: 3s
      timeout: 3s
      retries: 10

  anime-api:
    build:
      context: ./anime-api
    container_name: anime_api
    # restart: on-failure
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=psswd
      - DB_NAME=anime_db
      - PORT=5001
    depends_on:
      postgres-db:
        condition: service_healthy

  anime-ui:
    build:
      context: ./anime-ui
      args:
        - ANIME_API_URL=http://localhost:5001
    container_name: anime_ui
    ports:
      - "5002:5002"
    depends_on:
      - anime-api

volumes:
  pgdata:
